name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels: 'feat'

  - title: 'Bug Fixes'
    labels: 'fix'

  - title: 'Maintenance'
    label: 'chore'

  - title: 'Documentation'
    label: 'docs'

  - title: 'Continuos Integration'
    label: 'ci'

  - title: 'Build'
    label: 'build'

  - title: 'Performance'
    label: 'perf'

  - title: 'Refactor'
    label: 'refactor'

  - title: 'Style'
    label: 'style'

  - title: 'Test'
    label: 'test'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels: 'major'

  minor:
    labels: 'minor'

  patch:
    labels: 'patch'

  default: patch

exclude-labels:
  - 'skip-changelog'

exclude-contributors:
  - 'github-actions[bot]'
  - 'dependabot[bot]'

template: |
  ## Getting the project
  Get Docker Image from Dockerhub: https://hub.docker.com/r/thebouncingkoala/website
  Get Docker Image from Github Container Registry: https://github.com/thebouncingkoala/website/pkgs/container/website
  License: https://github.com/thebouncingkoala/website/blob/main/LICENSE
  Code of Conduct: https://github.com/thebouncingkoala/website/blob/main/.github/CODE_OF_CONDUCT.md

  ## New in website v$RESOLVED_VERSION

  $CHANGES
  $CONTRIBUTORS
