version: '3.9'
services:
  app:
    build: .
    command: yarn start
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
