name: Actions

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  release:
    types: [published]

jobs:
  analyze:
    name: Analyze
    uses: luisfalconmx/.github/.github/workflows/codeql.yml@main
    with:
      languages: javascript

  build:
    name: Build
    needs: analyze
    uses: luisfalconmx/.github/.github/workflows/builder.yml@main
    with:
      image-name: ${{github.event.repository.owner.login}}/${{github.event.repository.name}}

  test:
    name: Test
    needs: build
    uses: luisfalconmx/.github/.github/workflows/loader.yml@main
    with:
      image-name: ${{github.event.repository.owner.login}}/${{github.event.repository.name}}
      command: yarn test

  pre-release:
    name: Pre Release
    needs: test
    uses: luisfalconmx/.github/.github/workflows/releaser.yml@main
    with:
      pre-release: true

  release:
    name: Release
    needs: release
    uses: luisfalconmx/.github/.github/workflows/releaser.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      GHCR_USERNAME: ${{secrets.GHCR_USERNAME}}
      PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}

  deploy:
    name: Deploy
    needs: release
    uses: luisfalconmx/.github/.github/workflows/deployer.yml@main
    with:
      command: yarn run deploy
      image-name: ${{github.event.repository.owner.login}}/${{github.event.repository.name}}
