name: Actions

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  release:
    types: [published]

jobs:
  analyze:
    name: Analyze
    uses: luisfalconmx/.github/.github/workflows/analyzer.yml@main
    with:
      languages: javascript

  build:
    name: Build
    needs: analyze
    uses: luisfalconmx/.github/.github/workflows/builder.yml@main

  test:
    name: Test
    needs: build
    uses: luisfalconmx/.github/.github/workflows/tester.yml@main
    with:
      command: yarn run test:ci

  pre-release:
    name: Pre Release
    needs: test
    uses: luisfalconmx/.github/.github/workflows/maintainer.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}

  release:
    name: Release
    needs: pre-release
    uses: luisfalconmx/.github/.github/workflows/releaser.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      GHCR_USERNAME: ${{secrets.GHCR_USERNAME}}
      PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}

  deploy:
    name: Deploy
    needs: release
    uses: luisfalconmx/.github/.github/workflows/deployer.yml@main
    with:
      command: yarn run deploy
