name: Maintenance

on:
  schedule:
    - cron: 30 3 * * *

jobs:
  maintenance:
    name: Maintenance
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Github repository metadata
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Dynamic template render
        uses: varunsridharan/action-dynamic-readme@main
        with:
          GLOBAL_TEMPLATE_REPOSITORY: luisfalconmx/luisfalconmx
          files: README.md
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com
          commit_message: 'docs: update readme file [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Screenshot website
        uses: swinton/screenshot-website@v1.x
        with:
          source: ${{ env.REPOSITORY_HOMEPAGE_URL }}
          destination: screenshot.png

      - name: Download screenshot artifact
        uses: actions/download-artifact@v2
        with:
          name: screenshot
          path: .github/

      - name: Commit screenshot
        uses: test-room-7/action-update-file@v1.6.0
        with:
          github-token: ${{ secrets.PAT }}
          file-path: .github/screenshot.png
          commit-msg: 'docs: screenshot update [skip ci]'

      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          destination_container_repo: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_SLUG }}
          provider: dockerhub
          short_description: ${{ env.REPOSITORY_DESCRIPTION }}
          readme_file: 'README.md'

      - name: Synchronize labels
        uses: julb/action-manage-label@v1
        with:
          from: https://raw.githubusercontent.com/luisfalconmx/luisfalconmx/main/.github/config/labels.yml
          skip_delete: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
